.PHONY: example-builders
example-builders:
	cd labs \
	&& ./example-builders.sh &> ./example-builders.console

.PHONY: example-provisioners
example-provisioners:
	cd labs \
	&& ./example-provisioners.sh &> ./example-provisioners.console

.PHONY: wordpress-nginx
wordpress-nginx:
	cd labs \
	&& ./wordpress-nginx.sh &> ./wordpress-nginx.console
